site_name: Vortex
site_description: "Stability-focused pragmatic navigation for Compose Multiplatform, fork of Voyager."
repo_name: Vortex
repo_url: https://github.com/hristogochev/vortex

nav:
  - Overview: index.md
  - Setup: setup.md
  - Navigation:
      - Basic navigation: navigation/index.md
      - Nested navigation: navigation/nested-navigation.md
      - Bottom sheet navigation: navigation/bottom-sheet-navigation.md
      - Advanced navigation: navigation/advanced-navigation.md
      - Tab navigation: navigation/tab-navigation.md
  - State restoration: state-restoration.md
  - ScreenModel:
      - Overview: screenmodel/index.md
      - Koin integration: screenmodel/koin-integration.md
      - Kodein integration: screenmodel/kodein-integration.md
  - Transitions: transitions.md
  - Lifecycle: lifecycle.md
  - Deep links: deep-links.md
  - Stack API: stack-api.md
  - Work in progress: work-in-progress.md

theme:
  name: material
  logo: 'img/logo_vortex.png'
  favicon: 'img/favicon.ico'
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'blue'
      accent: 'cyan'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'indigo'
      accent: 'light-blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hristogochev


markdown_extensions:

  # Permalinks on top of pages
  - toc:
      permalink: true
  # Typography improvement
  - smarty
  # Footnotes
  - footnotes
  # Meta
  - meta
  # Do not attempt to guess what language code blocks are for
  - codehilite:
      guess_lang: false
  # Better understanding of '-'
  - pymdownx.betterem:
      smart_enable: all
  # Better caret handling
  - pymdownx.caret
  # Enables syntax highlighting for inline code blocks and adds support for additional formatting options like styling.
  - pymdownx.inlinehilite
  # Automatically converts URLs, email addresses, and references to clickable links.
  - pymdownx.magiclink
  # Automatically converts specific symbols or patterns into their typographic equivalents.
  - pymdownx.smartsymbols
  # Enhances fenced code blocks with support for nested content, custom rendering, and highlighting.
  - pymdownx.superfences
  # Just emojis
  - pymdownx.emoji
  # Adds support for collapsible details blocks, useful for hiding content by default.
  - pymdownx.details
  # Creates tabbed sections for displaying different content options.
  - pymdownx.tabbed:
      alternate_style: true
  # Enables rendering of Markdown tables.
  - tables
  # Adds support for admonition blocks, which are callouts boxes for notes, warnings, etc.
  - admonition