[versions]
agp = "9.3.2"
kotlin = "2.4.10"
# Sdks
android-minSdk = "23"
android-compileSdk = "37"
# Compose multiplatform
compose-multiplatform = "1.12.0"
compose-multiplatform-material3 = "1.9.0"
# Android specific
androidx-compose-activity = "1.13.0"
# Kodein extension
kodein = "7.33.0"
# Koin extension
koin = "4.2.2"
# Publishing
publish = "0.31.0"

[libraries]
# Compose
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-multiplatform-material3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-compose-activity" }

# Kodein extension
kodein = { module = "org.kodein.di:kodein-di-framework-compose-runtime", version.ref = "kodein" }

# Koin extension
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidMultiplatformLibrary = {id="com.android.kotlin.multiplatform.library", version.ref="agp"}
